media:
  - name: images
    label: Images
    input: media
    output: /media
    rename: safe
    categories: [image]

content:
  - name: home
    label: Home
    type: file
    path: _data/home.yml
    format: yaml
    fields:
      - name: intro
        label: Intro
        type: text
        required: true
      - name: image
        label: Image
        type: image
        options:
          media: images
          rename: safe
      - name: image_alt
        label: Image alt text
        type: string
  - name: thought
    label: Thought
    type: collection
    path: _thought
    format: yaml-frontmatter
    filename: "{year}-{month}-{day}-{primary}.md"
    view:
      fields: [title, date]
      primary: title
      sort: [date, title]
      default:
        sort: date
        order: desc
    fields: &entry_fields
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: body
        label: Body
        type: rich-text
        options:
          format: markdown
          media: images
          rename: safe
          switcher: true
  - name: life
    label: Life
    type: collection
    path: _life
    format: yaml-frontmatter
    filename: "{year}-{month}-{day}-{primary}.md"
    view:
      fields: [title, date]
      primary: title
      sort: [date, title]
      default:
        sort: date
        order: desc
    fields: *entry_fields
  - name: matter
    label: Matter
    type: collection
    path: _matter
    format: yaml-frontmatter
    filename: "{primary}.md"
    view:
      fields: [title, date]
      primary: title
      sort: [date, title]
      default:
        sort: date
        order: desc
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: link
        label: Project link
        type: string
      - name: body
        label: Body
        type: rich-text
        options:
          format: markdown
          media: images
          rename: safe
          switcher: true
